### ISSUE TITLE
Containerized Quarkus todo app fails to launch properly when deployed on AWS Fargate cluster

### ISSUE THREAD

**Issue by FrankBergemann** [quarkusio/todo-demo-app#16]
I created a Docker image for running quarkus todo list app in DEV mode using this Dockerfile:
`FROM openjdk:8-jdk-alpine

LABEL xxx xxx <xx@xx>

USER root

RUN wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P /tmp

RUN tar xf /tmp/apache-maven-3.6.3-bin.tar.gz -C /opt

RUN ln -s /opt/apache-maven-3.6.3/bin/mvn /usr/bin/mvn

RUN mkdir -p /usr/share/quarkus

COPY quarkus.tar.gz /usr/share/quarkus

RUN tar -xzf /usr/share/quarkus/quarkus.tar.gz -C /usr/share/quarkus

RUN rm -f /usr/share/quarkus/quarkus.tar.gz

EXPOSE 8080

CMD ["sh", "-c", "cd /usr/share/quarkus; mvn compile quarkus:dev"]`

When running this image locally on my Windows docker desktop the app is fully functional. The last lines of the console output after start-up are as expected:
`Hibernate: 
    INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Visit Quarkus web site', false, 2, 'https://quarkus.io')
Hibernate: 
    INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project', false, 3, 'https://github.com/quarkusio/quarkus/')
2020-10-24 11:58:57,417 INFO  [io.quarkus] (main) Quarkus 0.15.0 started in 3.878s. Listening on: http://[::]:8080
2020-10-24 11:58:57,422 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-h2, narayana-jta, resteasy, resteasy-jsonb]
`

However this image fails to lauch properly when transferred to Amazon AWS ECR and then deployed there using a ECS Fargate cluster.  When opening the app URL via the assigned public IP (http://54.86.53.85:8080/todo.html), the browser just displays a blank page with no content. Nonetheless, the browser tab title of the app is displayed correctly. The last lines of the console output after start-up in this case are:

` INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Introduction to Quarkus', true, 0, null)
2020-10-24 12:11:03
Hibernate:
Hibernate:
2020-10-24 12:11:03
2020-10-24 12:11:03
alter table Todo
alter table Todo
2020-10-24 12:11:03
add constraint UK_oxfuur9jdyqshux5rm7g7ga6c unique (title)
add constraint UK_oxfuur9jdyqshux5rm7g7ga6c unique (title)
2020-10-24 12:11:03
id bigint not null,
id bigint not null,
2020-10-24 12:11:03
completed boolean not null,
completed boolean not null,
2020-10-24 12:11:03
ordering integer,
ordering integer,
2020-10-24 12:11:03
title varchar(255),
title varchar(255),
2020-10-24 12:11:03
url varchar(255),
url varchar(255),
2020-10-24 12:11:03
primary key (id)
primary key (id)
2020-10-24 12:11:03
)
)
`

As can be seen, the message `Listening on: http://[::]:8080` shown at the end of the console output from the locally run image is missing here.

Have you got any idea what might go wrong in the AWS case?

In the ECR Task that is to be created inside the ECS Fargate cluster to run the container, I explictly enabled communication via port 8080. Can it be that special precautions must be taken related to the quarkus todo log mesages `Established TCP socket on 64572` and/or `Listening for transport dt_socket at address: 5005`?

**Comment by cescoffier** [comment]
This does not seem to be related to the application itself. I would recommend opening an issue in Quarkus directly.

**Comment by FrankBergemann** [comment]
This is working now.
