### ISSUE TITLE
Health ckeck URL dosen't work

### ISSUE THREAD

**Issue by FrankBergemann** [quarkusio/todo-demo-app#17]
Hi Clement,
Quarkus todo application is running fine on my local Win10 box when launched by `mvn compile quarkus:dev`. However, I noticed that the health check URL: `http://localhost:8080/health` returns the error message: 
`RESTEASY003210: Could not find resource for full path: http://localhost:8080/health/`
I would be expecting: `200 OK`. Having this working is IMHO required when deploying the application in AWS cloud.
Can you help?
Kind regards
-- Frank

**Comment by cescoffier** [comment]
I don't believe we added the Quarkus health extension.

**Comment by FrankBergemann** [comment]
Would you mind addidng it? I think the added value would be considerable as the Quarkus technology is aiming particularly at the cloud world. And IMHO serious cloud implementations rely on health check mechanisms for robust operation. If you don't want to do it I'd recommend to remove the health check URL from the readme.md file. -- Frank

**Comment by cescoffier** [comment]
Yes, we should add, as well as metrics I would say.

**Comment by FrankBergemann** [comment]
I checked. Health check is working now. Thx.
