### ISSUE TITLE
Maven package comand fails when trying to use -Dnative-image.docker-build=true option

### ISSUE THREAD

**Issue by FrankBergemann** [quarkusio/todo-demo-app#22]
Hi,
I noticed that on Win10 host the command
`mvn package -Pnative -Dnative-image.docker-build=true`
in todo-demo-app home directory fails with error message:
`Unknown lifecycle phase ".docker-build=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize ...`

I have further questions:
1. Is todo-demo-app designed to be used with postgress DB in JVM mode? I'd appreciate to have this working, also in docker containers.
2. What is the need to expose port 5432 in postgress-DB mode using docker run cmd?
3. Could you provide a docker-compose.yml file to launch quarkus-todo and a connected postgress-DB each in its own container?
I struggle to get this working as I don't know how to configure the mapping of port 5432.
Kind regards
-- Frank

**Comment by gsmet** [comment]
I just tried and it works well here.

Which version of Maven and which OS are you using? It's the second report of this sort that we have so there must be something fishy.

**Comment by FrankBergemann** [comment]
I checked again. The error was on my side. It was an issue with Windows powershell cmd-line tool. It is working when using a different shell tool.Sorry for the inconvenience. I close the ticket.
