### ISSUE TITLE
Can I run the postgresql branch of todo app in JVM mode? - Compilation to native fails with latest graalvm compiler on WIN10  

### ISSUE THREAD

**Issue by FrankBergemann** [quarkusio/todo-demo-app#23]
Hi,
Can I run the postgresql branch of the todo app in JVM mode?
I'm trying to do that on Win10 but it fails. Using the info from readme.md, I first launched postgresql DB in a docker container:
`docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0     --name postgres-quarkus-rest-http-crud     -e POSTGRES_USER=restcrud     -e POSTGRES_PASSWORD=restcrud     -e POSTGRES_DB=rest-crud     -p 5432:5432 postgres:latest`
As output messages show, this is working and the DB is ready to accept connections, see attachment.
Then I run
```
mvn clean package
java -jar target/todo-backend-1.0-SNAPSHOT-runner.jar
```
The app launches and log messages show the Todo table is created and 4 rows inserted into it. However, if I open the app via
`localhost:8080`
The app shows no rows and exception messages appear in the console (see attachments)
Please find used java and maven versions attached.

I furthermore noticed that compiling into native mode fails with latest GRAALVM compiler version for Windows
`C:\Program Files\GraalVM\graalvm-ce-java8-windows-amd64-21.0.0.2\graalvm-ce-java8-21.0.0.2 `
Here are the messages to the console:
`
$ mvn clean package -Pnative
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< io.quarkus.sample:todo-backend >-------------------
[INF       O] Building todo-backend 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ todo-backend ---
[INFO] Deleting C:\Users\BERGEF\onedrive\git\todo-app\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ todo-backend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 288 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ todo-backend ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\BERGEF\onedrive\git\todo-app\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ todo-backend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C          :\Users\BERGEF\onedrive\git\todo-app\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile)                              m @ todo-backend ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ todo-backend ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2                     .4:jar (default-jar) @ todo-backend ---
[INFO] Building jar: C:\Users\BERGEF\onedrive\git\todo-app\target\todo-backend-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.15.0:build (default) @ todo-backend ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Beta3
[INFO] [org.hibernate.jpa.boot.internal.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the cla
sspath
[INFO] [org.hibernate.Version] HHH000412: Hibernate Core {5.4.2.Final}
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1995ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: C:\Users\BERGEF\onedrive\git\todo-app\target\todo-backend-1
.0-SNAPSHOT-runner.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.15.0:native-image (default) @ todo-backend ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server
 VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] C:\Program Files\GraalVM\graalvm-ce-java8-windows-amd64-21.0.0.2\graa
lvm-ce-java8-21.0.0.2\bin\native-image.cmd -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscaveng
e.CollectionPolicy$BySpaceAndTime -jar todo-backend-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+
ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI
-H:-UseServiceLoaderFeature -H:+StackTrace
[INFO] --------------------              ----------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -------------------------------------------------------------              -----------
[INFO] Total time:  10.785 s
[INFO] F          inished at: 2021-04-08T11:31:23+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.15.0:native-image (default) on project todo-backend: Fail
ed to generate a native image: Failed to build native image: Cannot run program "C:\Program Files\GraalVM\graalvm-ce-java8-windows-amd64-21.0.0.2\graalvm-ce-ja
va8-21.0.0.2\bin\native-image.cmd" (in directory "C:\Users\BERGEF\onedrive\git\todo-app\target"): CreateProcess error=2, Das System kann die angegebene Datei nich
t finden -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR       ] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and           possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`
Kind regards
-- Frank

**Comment by FrankBergemann** [comment]
![2021-04-08_11h16_23](https://user-images.githubusercontent.com/54316676/114013453-d48d1000-9867-11eb-8fa5-e84fc3d1b528.png)
![2021-04-08_11h18_01](https://user-images.githubusercontent.com/54316676/114013579-fb4b4680-9867-11eb-940c-65acbe2b8a6b.png)
![2021-04-08_11h18_28](https://user-images.githubusercontent.com/54316676/114013593-fdada080-9867-11eb-9efe-28e92d9b8491.png)
![2021-04-08_11h19_43](https://user-images.githubusercontent.com/54316676/114013611-00a89100-9868-11eb-9b61-a861435e586e.png)

**Comment by FrankBergemann** [comment]
Are there any news on this issue? I'm using the app for demo and learning purposes heavily and the issue is blocking me. Let me know if you have further questions.

**Comment by FrankBergemann** [comment]
Same behavior when sources are compiled with openjdk-11.

**Comment by cescoffier** [comment]
The error message says that C:\Program Files\GraalVM\graalvm-ce-
java8-windows-amd64-21.0.0.2\graalvm-ce-ja va8-21.0.0.2\bin\native-image.cmd
does not exist. Can you check it does exist?

**Comment by FrankBergemann** [comment]
The file native-image.cmd indeed doesn't exist within the graalvm-21.0.0.2. installation on my Win10 machine. I downloaded the graalvm package from the offical graalvm download site.

By the way: native compilation is not my focus. I would be happy to use quarkus todo in jvm mode and (containerized) postgres DB. If I'm getting this to work in containers in native mode: fine as well, of course.

**Comment by cescoffier** [comment]
You can try https://github.com/cescoffier/quarkus-todo-app. I believe it was recently tested on windows.

**Comment by FrankBergemann** [comment]
I tried to use the project from the post above, but without success. Running the app from a jar file was failing with exceptions. Issuing compile quarkus:dev, brings up the app. But then the postgres DB isn't used and tables are dropped and recreated upon every app restart. My aim, however, was to have todo app entries persisted in the DB. I can post logs if needed.

Has the postgresql branch of this project recently been verified to work on linux as desribed in readme.md?

**Comment by cescoffier** [comment]
it's because it used Dev Services and is configured to drop the table on restart. This is configurable in the `application.properties`.

**Comment by FrankBergemann** [comment]
Hi Clement, Using your advice, the todo entries are persisted as desired. It's a big step forward for me; thanks a lot!
-- Frank
