### ISSUE TITLE
Quarkus: Maven compile step fails on Win7 machine

### ISSUE THREAD

**Issue by FrankBergemann** [quarkusio/todo-demo-app#5]
I followed the steps described in https://quarkus.io/guides/getting-started-guide to install and run on my local Win7-64 computer. 

Step mvn io.quarkus:quarkus-maven-plugin:0.21.1:create succeeded without error messages

However, the next step ./mvnw compile quarkus:dev failed with error message

Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.ThreadPoolSetup#createExecutor threw an exception: java.lang.Error: java.lang.NoSuchFieldException: override

See attached log file containing mvn -X output.

Installed is 

java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
[mvn-build-messages.log](https://github.com/quarkusio/todo-demo-app/files/3529047/mvn-build-messages.log)

mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: C:\Program Files\Apache\Maven\apache-maven-3.6.1
Java version: 12.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-12.0.1
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Does somebody have a clue what goes wrong?

**Comment by rsvoboda** [comment]
Java version "12.0.1" is not supported yet, see https://quarkus.io/get-started/ - You need JDK 8 or 11

There is ongoing effort to enable Java 12 and 13 with Quarkus, I assume it should be available soon(-ish).
