### ISSUE TITLE
[quarkus] todo-demo-app packaged to jar file fails to run stand-alone

### ISSUE THREAD

**Issue by FrankBergemann** [quarkusio/todo-demo-app#9]
I cloned this repo and ran
`mvn package`
on a Win10 machine with the aim to create a stand-alone executable jar file. This created **todo-backend-1.0-SNAPSHOT-runner.jar** in the target/ folder as expected.
However, if I copy **target\todo-backend-1.0-SNAPSHOT-runner.jar** into an empty directory and run 
`java -jar target\todo-backend-1.0-SNAPSHOT-runner.jar`
execution fails with error message
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/runtime/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
...
```
Now, if I add the complete folder **src/** to the execution directory and run the java cmd again everything works fine, obviously beause the missing classes are found in the src/-folder.
Would it be possible add the necessary files to the jar, so that this error is avoided?
I'm using maven 3.6.3.

**Comment by cescoffier** [comment]
Quarkus does not build a _fat jar_ by default. You need to copy the runner and the `libs` directory or configure the project to build a _fat jar_.
